# Generated by Django 4.2.4 on 2023-09-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_remove_price_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(max_length=5, verbose_name='Precio'),
        ),
    ]
