# Generated by Django 4.2.4 on 2023-09-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_alter_price_image_alter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon_class', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='price',
            name='features',
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='price',
            name='services',
            field=models.ManyToManyField(to='prices.plan', verbose_name='Servicios'),
        ),
    ]
