# Generated by Django 4.2.4 on 2023-09-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_plan_remove_price_features_alter_price_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='icon_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
