# Generated by Django 4.2.4 on 2023-09-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_plan_show_in_basic_plan_show_in_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='icon_class',
        ),
    ]
