# Generated by Django 4.2.4 on 2023-09-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(max_length=50, null=True, verbose_name='Icono'),
        ),
    ]
