# Generated by Django 4.2.4 on 2023-09-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('profession', models.CharField(max_length=100, verbose_name='Profesión')),
                ('content', models.TextField(verbose_name='Testimonio')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
    ]
