# Generated by Django 4.2.4 on 2023-09-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_testimonial_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['created'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
    ]
