# Generated by Django 4.2.4 on 2023-09-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='socialnet',
        ),
    ]
