# Generated by Django 4.2.4 on 2023-09-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('about', '0002_remove_about_socialnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='socialnet',
            field=models.ManyToManyField(to='social.social', verbose_name='Redes'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
    ]
